name: CI
on: [push]
jobs:
  build:
    name: Build and test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: pnpm i

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build
